apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-stats-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eykn2z/todo-stats-app.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
